apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-pipeline
spec:
  selector:
    matchLabels:
      app: pipeline-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: pipeline-k8s
    spec:
      containers:
        - name: pipeline-k8s
          image: pipeline-k8s:1.0
          ports:
            - containerPort: 9090
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: pipeline-k8s
spec:
  selector:
    app: pipeline-k8s
  ports:
    - protocol: "TCP"
      port: 9090 # The port that the service is running on in the cluster
      targetPort: 9090 # The port exposed by the service
  type: NodePort # type of the service.