version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=pipeline"
    ports:
      - "3306:3306"
    networks:
      app:
  springapp:
    depends_on:
      - mysql-standalone
    image: app_01
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/pipeline?autoReconnect=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"

    networks:
      app:
networks:
  app:
