apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-pipeline-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: spring-k8s
          imagePullPolicy: IfNotPresent
          image: spring:latest
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: pipeline
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-pipeline-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 9090
  type: NodePort