apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-pipeline-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: spring-k8s
          imagePullPolicy: Never
          image: spring:latest
          ports:
            - containerPort: 9090
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql

            - name: DB_NAME  # Setting Database name from configMap
              value: pipeline

            - name: DB_USERNAME  # Setting Database username from Secret
              value: root

            - name: DB_PASSWORD # Setting Database password from Secret
              value: password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-pipeline-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 9090 # The port that the service is running on in the cluster
      targetPort: 9090 # The port exposed by the service
  type: NodePort # type of the service.
