server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pipeline?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
    generate-ddl: true


### GRAPHQL
# Graphql
graphql:
  servlet:
    mapping: /apis/graphql

### DATOS
api:
  url:
    cdmx: https://datos.cdmx.gob.mx/api/3/action/datastore_search?resource_id=ad360a0e-b42f-482c-af12-1fd72140032e&limit=207
